[package]
name = "magnetite_rs"
version = "0.1.0"
authors = ["simoin <lfzeng34@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"

actix-web = "3"

lazy_static = "1.4.0"
libxml = { git = "https://github.com/simoin/rust-libxml.git", branch = "win" }

reqwest = { version = "0.10", features = ["json", "cookies"] }

chrono = "0.4.15"
rss = "1.9.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"