[package]
name = "rsshub_rs"
version = "0.1.0"
authors = ["simoin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
anyhow = "1.0"

minreq = { version = "2.2.1", features = ["https-native", "json-using-serde", "proxy"] }
libxml = { git = "https://github.com/simoin/rust-libxml.git", branch = "win" }

chrono = "0.4.15"

rss = "1.9.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

actix-web = "3"